version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: always
    ports:
      - 5432:5432
    networks:
      - net
    volumes:
      - ./postgres:/var/lib/postgresql


  redis:
    image: "redis:alpine"
    restart: 'always'
    networks:
      - net
    ports:
      - 6379:6379


#
#  tgbot:
#    container_name: aipgram
#    build:
#      context: .
#    command: python app.py
#    networks:
#      - net
#    env_file:
#      - ".env"
#    volumes:
#      - .:/src
#    depends_on:
#      - db
#      - redis

networks:
  net:
    driver: bridge
